[metadata]
name = aafragpy
version = 2.0.2
author = Sergey Koldobskiy et al.
author_email = sergey.koldobskiy@oulu.fi
description = Python package for calculation of secondary particle production in nuclear interactions
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE
platforms = any
url = https://github.com/aafragpy/aafragpy
project_urls =
    Bug Tracker = https://github.com/aafragpy/aafragpy/issues
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Physics

[options]
packages = find:
python_requires = >=3.8
install_requires =
    numpy>=1.18.0
include_package_data = True

[options.packages.find]
include = 
    aafragpy*
exclude =
    tests*

[options.package_data]
aafragpy = 
    Tables/*.npz